version: '3.7'

services:

  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: url-shortener
    entrypoint: wait-for-it.sh url-shortener-db:27017 -t 30 -- npm start
    networks:
      - url-shortener-network
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    restart: always
    depends_on:
      - url-shortener-db

  url-shortener-db:
    image: mongo
    restart: always
    container_name: url-shortener-db
    networks:
      - url-shortener-network
    volumes:
      - url-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

volumes:
  url-db:

networks:
  url-shortener-network:
    name: url-shortener-network
    driver: bridge